export type AuthenticatedExecutionContext = Readonly<{
  /** Stable identity established by the trusted server authentication boundary. */
  actorId: string;
  /** Unique execution identity generated by the trusted server boundary. */
  runId: string;
  /** Task workspace derived from the authoritative task, not client input. */
  workspaceId: string;
  /** Correlates one dispatch attempt across provider, evidence and audit records. */
  correlationId: string;
}>;

export type ExecutionIdentitySource = "authenticated-session" | "trusted-server";

export type ExecutionIdentityErrorCode =
  | "MISSING_ACTOR"
  | "MISSING_RUN"
  | "MISSING_WORKSPACE"
  | "MISSING_CORRELATION"
  | "UNTRUSTED_IDENTITY_SOURCE";

export type ExecutionIdentityError = Readonly<{
  code: ExecutionIdentityErrorCode;
  message: string;
}>;

/**
 * Validate an identity that has already crossed the trusted authentication boundary.
 * This deliberately does not manufacture authentication: callers must supply a
 * context produced by an authenticated server adapter.
 */
export function validateAuthenticatedExecutionContext(
  context: AuthenticatedExecutionContext,
  source: ExecutionIdentitySource,
): ExecutionIdentityError[] {
  const errors: ExecutionIdentityError[] = [];
  if (source !== "authenticated-session" && source !== "trusted-server") {
    errors.push({ code: "UNTRUSTED_IDENTITY_SOURCE", message: "execution identity source is not trusted" });
  }
  if (!context.actorId.trim()) errors.push({ code: "MISSING_ACTOR", message: "authenticated actor is required" });
  if (!context.runId.trim()) errors.push({ code: "MISSING_RUN", message: "durable run identity is required" });
  if (!context.workspaceId.trim()) errors.push({ code: "MISSING_WORKSPACE", message: "authoritative workspace scope is required" });
  if (!context.correlationId.trim()) errors.push({ code: "MISSING_CORRELATION", message: "dispatch correlation identity is required" });
  return errors;
}

export function isAuthenticatedExecutionContext(
  context: AuthenticatedExecutionContext,
  source: ExecutionIdentitySource,
): boolean {
  return validateAuthenticatedExecutionContext(context, source).length === 0;
}
