import type { IncomeStreamKit } from "./income-stream-kit";

export const INCOME_STREAM_PORTFOLIO: readonly IncomeStreamKit[] = [
  {
    id: "local-opportunity-leads",
    industry: "local services",
    customer: "small local operators",
    problem: "qualified local demand is fragmented",
    value: "evidence-backed opportunity discovery",
    paymentMechanism: "lead",
    autonomyCeiling: "L2",
    state: "EXPERIMENTAL",
    humanGates: ["human reviews external outreach and any commercial handoff"],
    killCriteria: ["no qualified demand signal", "unsupported claims", "poor repeatability"],
    evidenceRequired: ["real demand signal", "canonical supply evidence", "action outcome"],
    dependencies: ["findSupply()", "provenance", "human review"],
  },
  {
    id: "provider-intelligence",
    industry: "professional services",
    customer: "small expert teams",
    problem: "market intelligence is fragmented and expensive to maintain",
    value: "verified recurring intelligence packets",
    paymentMechanism: "subscription",
    autonomyCeiling: "L2",
    state: "EXPERIMENTAL",
    humanGates: ["human reviews claims before customer delivery"],
    killCriteria: ["no verified signal", "no repeat value", "delivery cost too high"],
    evidenceRequired: ["source evidence", "independent verification", "customer value signal"],
    dependencies: ["provenance", "verification", "bounded delivery"],
  },
  {
    id: "opportunity-research-kits",
    industry: "small business",
    customer: "operators evaluating new markets",
    problem: "market research is slow and hard to compare",
    value: "human-reviewed evidence packets",
    paymentMechanism: "service",
    autonomyCeiling: "L1",
    state: "EXPERIMENTAL",
    humanGates: ["human approves every external deliverable"],
    killCriteria: ["unsupported research", "no customer usefulness", "delivery cost too high"],
    evidenceRequired: ["primary sources", "dated evidence", "uncertainty record"],
    dependencies: ["research workflow", "independent review"],
  },
  {
    id: "partner-discovery",
    industry: "communities",
    customer: "community and network operators",
    problem: "relevant partners are difficult to discover and qualify",
    value: "evidence-backed partner capability maps",
    paymentMechanism: "licensing",
    autonomyCeiling: "L1",
    state: "EXPERIMENTAL",
    humanGates: ["human approves partner contact and commercial terms"],
    killCriteria: ["no qualified partner signal", "misleading fit claims"],
    evidenceRequired: ["public partner evidence", "fit rationale", "human confirmation"],
    dependencies: ["canonical discovery", "provenance"],
  },
  {
    id: "event-locality-intelligence",
    industry: "events and hospitality",
    customer: "local/event operators",
    problem: "verified local opportunity context is fragmented",
    value: "truthful locality and event intelligence",
    paymentMechanism: "referral",
    autonomyCeiling: "L1",
    state: "EXPERIMENTAL",
    humanGates: ["human reviews referral terms and external publication"],
    killCriteria: ["stale data", "thin locality evidence", "no useful action"],
    evidenceRequired: ["fresh locality evidence", "source provenance", "action result"],
    dependencies: ["locality API", "canonical world data", "freshness checks"],
  },
];
