/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GiveRouteImport } from './routes/give'
import { Route as HelpRouteImport } from './routes/help'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as LifeListRouteImport } from './routes/life-list'
import { Route as MakeRouteImport } from './routes/make'
import { Route as NeedRouteImport } from './routes/need'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NeedIdRouteImport } from './routes/need.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeListRoute = LifeListRouteImport.update({
  id: '/life-list',
  path: '/life-list',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeRoute = MakeRouteImport.update({
  id: '/make',
  path: '/make',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedRoute = NeedRouteImport.update({
  id: '/need',
  path: '/need',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedIdRoute = NeedIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/give': typeof GiveRoute
  '/help': typeof HelpRoute
  '/journey': typeof JourneyRoute
  '/life-list': typeof LifeListRoute
  '/make': typeof MakeRoute
  '/need': typeof NeedRouteWithChildren
  '/profile': typeof ProfileRoute
  '/need/$id': typeof NeedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/give': typeof GiveRoute
  '/help': typeof HelpRoute
  '/journey': typeof JourneyRoute
  '/life-list': typeof LifeListRoute
  '/make': typeof MakeRoute
  '/need': typeof NeedRouteWithChildren
  '/profile': typeof ProfileRoute
  '/need/$id': typeof NeedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/give': typeof GiveRoute
  '/help': typeof HelpRoute
  '/journey': typeof JourneyRoute
  '/life-list': typeof LifeListRoute
  '/make': typeof MakeRoute
  '/need': typeof NeedRouteWithChildren
  '/profile': typeof ProfileRoute
  '/need/$id': typeof NeedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/give'
    | '/help'
    | '/journey'
    | '/life-list'
    | '/make'
    | '/need'
    | '/profile'
    | '/need/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/give'
    | '/help'
    | '/journey'
    | '/life-list'
    | '/make'
    | '/need'
    | '/profile'
    | '/need/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/give'
    | '/help'
    | '/journey'
    | '/life-list'
    | '/make'
    | '/need'
    | '/profile'
    | '/need/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GiveRoute: typeof GiveRoute
  HelpRoute: typeof HelpRoute
  JourneyRoute: typeof JourneyRoute
  LifeListRoute: typeof LifeListRoute
  MakeRoute: typeof MakeRoute
  NeedRoute: typeof NeedRouteWithChildren
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-list': {
      id: '/life-list'
      path: '/life-list'
      fullPath: '/life-list'
      preLoaderRoute: typeof LifeListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make': {
      id: '/make'
      path: '/make'
      fullPath: '/make'
      preLoaderRoute: typeof MakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/need': {
      id: '/need'
      path: '/need'
      fullPath: '/need'
      preLoaderRoute: typeof NeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/need/$id': {
      id: '/need/$id'
      path: '/$id'
      fullPath: '/need/$id'
      preLoaderRoute: typeof NeedIdRouteImport
      parentRoute: typeof NeedRoute
    }
  }
}

interface NeedRouteChildren {
  NeedIdRoute: typeof NeedIdRoute
}

const NeedRouteChildren: NeedRouteChildren = {
  NeedIdRoute: NeedIdRoute,
}

const NeedRouteWithChildren = NeedRoute._addFileChildren(NeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GiveRoute: GiveRoute,
  HelpRoute: HelpRoute,
  JourneyRoute: JourneyRoute,
  LifeListRoute: LifeListRoute,
  MakeRoute: MakeRoute,
  NeedRoute: NeedRouteWithChildren,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
